### ISSUE TITLE
Cannot exacute the program

### ISSUE THREAD

**Issue by maromaSamsa** [philipturner/ar-multipendulum#3]
Hi @philipturner, 
I just downlaod your repo, add ARHeadsetKit package, change bunde identifier and start exacution on Xcode, but it seems this repo had missing some file:

1. Metal_Utilities_Combined
2. Launch Screen

the error message:
AR MultiPendulum Group 1 issues
 - Target Integrity Group
 >AR MultiPendulum.xcodeproj This Copy Files build phase contains a reference to a missing file 'ARHeadsetKit.framework'.

how should I fix it?

**Comment by philipturner** [comment]
The setup for AR MultiPendulum is quite involved. Read through tutorial 9 of the ARHeadsetKit tutorial series. You can skip all the other tutorials and go straight to tutorial 9, although it might be helpful to do tutorials 1 and 2 beforehand. It shows a more complicated way to link ARHeadsetKit to your app. AR MultiPendulum must depend on the Metal shader utilities and launch screen of ARHeadsetKit, which cannot be done through the Swift Package Manager alone.

> AR MultiPendulum.xcodeproj This Copy Files build phase contains a reference to a missing file 'ARHeadsetKit.framework'.

This is because it's depending on ARHeadsetKit as an Xcode framework instead of as a Swift package.

---

Let me know whether you are able to compile AR MultiPendulum after repeating the steps of tutorial 9.

**Comment by maromaSamsa** [comment]
@philipturner 
Thanks a lot, I have compiled the project successfully
